[build]
target = "index.html"
release = false
dist = "dist"
public_url = "/"
filehash = true
inject_scripts = true

[watch]
watch = []
ignore = []

[serve]
address = "127.0.0.1"
port = 8080
open = false
no_autoreload = false

[clean]
dist = "dist"
cargo = false


# Authentication proxy
[[proxy]]
backend = "http://auth-proxy:9001"
