################################################################################
# Docker containers
################################################################################


################################################################################
# Services
################################################################################
services:

  ##############################################################################
  # System containers
  ##############################################################################

  # Load balancer
  balancer:
    container_name: meower_balancer
    build:
      context: .
      dockerfile: ./docker/system/balancer/Dockerfile
    ports:
      - ${BALANCER_PORT}:8080
    volumes:
      - ./docker/system/balancer/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - auth_layer

  # Authentication
  auth_layer:
    container_name: meower_auth
    ports:
      - ${AUTH_LAYER_PORT}:9000
    build:
      context: .
      dockerfile: ./docker/system/auth/Dockerfile
    volumes:
      - ./system/layer/auth:/system/layer/auth
      - ./system/database/entity:/system/database/entity
      - ./system/util:/system/util
    environment:
      SYSTEM_URL: ${SYSTEM_URL}
      DEBUG_MODE: ${DEBUG_MODE}
      PORT: 9000
      DATABASE_URL: ${DATABASE_URL}
      FALLBACK_LOCALE: en
      JWT_ISSUE: ${JWT_ISSUE}
      JWT_AUDIENCE: ${JWT_AUDIENCE}
      JWT_EXPIRATION_MINUTES: ${JWT_EXPIRATION_MINUTES}
      JWT_SECRET: ${JWT_SECRET}
      SYSTEM_EMAIL_ADDRESS: ${SYSTEM_EMAIL_ADDRESS}
      SMTP_TLS: ${SMTP_TLS}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
    working_dir: /system/layer/auth
    command: "cargo watch -x run"
    depends_on:
      - postgres
    tty: true

  # Postgres
  postgres:
    container_name: meower_postgres
    build:
      context: .
      dockerfile: ./docker/system/postgres/Dockerfile
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: --encoding=UTF-8
    command: ["-c", "max_connections=200"]
    restart: always
    tty: true


  ##############################################################################
  # Development tools
  ##############################################################################

  # Development tools
  dev:
    container_name: meower_dev
    build:
      context: .
      dockerfile: ./docker/base/dev/Dockerfile
    volumes:
      - ./system:/system
    environment:
      DATABASE_URL: ${DATABASE_URL}
    tty: true

  # mailhog
  mailhog:
    container_name: meower_mailhog
    image: mailhog/mailhog:latest
    ports:
      - ${MAILHOG_PORT}:8025
      - ${MAILHOG_SMTP_PORT}:1025
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /tmp
    volumes:
      - mailhog-data:/tmp

  # tbls
  tbls:
    container_name: meower_tbls
    image: k1low/tbls:latest
    volumes:
      - ${TBLS_OUTPUT_PATH}:/work
    working_dir: /work
    environment:
      TBLS_DSN: ${TBLS_DSN}
      TBLS_DOC_PATH: /work/${TBLS_DOC_PATH}
    depends_on:
      - postgres
    tty: true


################################################################################
# Volumes
################################################################################
volumes:
  pg-data:
  mailhog-data:
