################################################################################
# Docker containers
################################################################################


################################################################################
# Services
################################################################################
services:

  ##############################################################################
  # System containers
  ##############################################################################

  # Load balancer
  balancer:
    container_name: meower_balancer
    build:
      context: .
      dockerfile: ./docker/system/balancer/Dockerfile
    ports:
      - ${BALANCER_PORT}:8080
    volumes:
      - ./docker/system/balancer/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - auth_server
      - spa
      - api

  # Auth server
  auth_server:
    container_name: meower_auth_server
    build:
      context: .
      dockerfile: ./docker/system/auth/Dockerfile
    volumes:
      - ./system/auth_server:/system/auth_server
      - ./proto/ui_catalog/assets/css/style.css:/system/auth_server/assets/css/ui.css
      - ./system/database/entity:/system/database/entity
      - ./system/util:/system/util
    environment:
      SYSTEM_URL: ${SYSTEM_URL}
      DEBUG_MODE: ${DEBUG_MODE}
      PORT: ${AUTH_SERVER_PORT}
      DATABASE_URL: ${DATABASE_URL}
      FALLBACK_LOCALE: en
      JWT_ISSUE: ${JWT_ISSUE}
      JWT_AUDIENCE: ${JWT_AUDIENCE}
      JWT_EXPIRATION_MINUTES: ${JWT_EXPIRATION_MINUTES}
      JWT_SECRET: ${JWT_SECRET}
      SYSTEM_EMAIL_ADDRESS: ${SYSTEM_EMAIL_ADDRESS}
      SMTP_TLS: ${SMTP_TLS}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SPA_URL: ${SPA_URL}
    working_dir: /system/auth_server
    command: "cargo watch -x run"
    depends_on:
      - postgres
    tty: true

  # SPA
  spa:
    container_name: meower_spa
    build:
      context: .
      dockerfile: ./docker/system/spa/Dockerfile
    volumes:
      - ./system/service/spa:/system/service/spa
      - ./proto/ui_catalog/assets/scss:/system/service/spa/public/scss
      - ./system/service/schema:/system/service/schema
    environment:
      API_URL: ${API_URL}
    working_dir: /system/service/spa
    command: "trunk serve --address 0.0.0.0 --release --port ${SPA_PORT}"
    tty: true

  # API
  api:
    container_name: meower_api
    build:
      context: .
      dockerfile: ./docker/system/api/Dockerfile
    volumes:
      - ./system/service/api:/system/service/api
      - ./system/service/schema:/system/service/schema
      - ./system/database/entity:/system/database/entity
      - ./system/util:/system/util
    environment:
      PORT: ${API_PORT}
      DATABASE_URL: ${DATABASE_URL}
      FALLBACK_LOCALE: en
      JWT_ISSUE: ${JWT_ISSUE}
      JWT_AUDIENCE: ${JWT_AUDIENCE}
      JWT_EXPIRATION_MINUTES: ${JWT_EXPIRATION_MINUTES}
      JWT_SECRET: ${JWT_SECRET}
      SYSTEM_EMAIL_ADDRESS: ${SYSTEM_EMAIL_ADDRESS}
      SMTP_TLS: ${SMTP_TLS}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
    working_dir: /system/service/api
    command: "cargo watch -x run"
    tty: true

  # Postgres
  postgres:
    container_name: meower_postgres
    build:
      context: .
      dockerfile: ./docker/system/postgres/Dockerfile
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: --encoding=UTF-8
    command: ["-c", "max_connections=200"]
    restart: always
    tty: true


  ##############################################################################
  # Development tools
  ##############################################################################

  # Development tools
  dev:
    container_name: meower_dev
    build:
      context: .
      dockerfile: ./docker/base/dev/Dockerfile
    volumes:
      - ./system:/system
      - ./proto:/proto
    environment:
      DATABASE_URL: ${DATABASE_URL}
    tty: true

  # mailhog
  mailhog:
    container_name: meower_mailhog
    image: mailhog/mailhog:latest
    ports:
      - ${MAILHOG_PORT}:8025
      - ${MAILHOG_SMTP_PORT}:1025
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /tmp
    volumes:
      - mailhog-data:/tmp

  # tbls
  tbls:
    container_name: meower_tbls
    image: k1low/tbls:latest
    volumes:
      - ${TBLS_OUTPUT_PATH}:/work
    working_dir: /work
    environment:
      TBLS_DSN: ${TBLS_DSN}
      TBLS_DOC_PATH: /work/${TBLS_DOC_PATH}
    depends_on:
      - postgres
    tty: true

  # UI catalog
  ui:
    container_name: meower_ui
    build:
      context: .
      dockerfile: ./docker/dev/ui/Dockerfile
    ports:
      - ${UI_CATALOG_PORT}:8030
    volumes:
      - ./proto/ui_catalog:/proto/ui_catalog
      - ui-catalog-node_modules:/proto/ui_catalog/node_modules
    working_dir: /proto/ui_catalog
    command: "npx gulp"
    tty: true


################################################################################
# Volumes
################################################################################
volumes:
  pg-data:
  mailhog-data:
  ui-catalog-node_modules:
