################################################################################
# Docker containers
################################################################################


################################################################################
# Services
################################################################################
services:

  ##############################################################################
  # System containers
  ##############################################################################

  # Auth server
  auth:
    container_name: meower_auth
    build:
      context: .
      dockerfile: ./docker/services/auth/Dockerfile
    ports:
      - ${AUTH_PORT}:${AUTH_PORT}
    volumes:
      - ./system/auth:/system/auth
      - ./system/common:/system/common
      - ./proto/ui_catalog/assets/css/style.css:/system/auth/core/assets/css/ui.css
      - ./env/${ENV}/${JWT_PRIVATE_KEY}:/system/auth/core/env/${JWT_PRIVATE_KEY}
    environment:
      PORT: ${AUTH_PORT}
      URL: ${AUTH_URL}
      DATABASE_URL: ${AUTH_DB_URL}
      FALLBACK_LOCALE: ${FALLBACK_LOCALE}
      CLIENT_ID_KEY: ${CLIENT_ID_KEY}
      CLIENT_SECRET_KEY: ${CLIENT_SECRET_KEY}
      SMTP_HOST: ${AUTH_SMTP_HOST}
      SMTP_PORT: ${AUTH_SMTP_PORT}
      SMTP_USER: ${AUTH_SMTP_USER}
      SMTP_PASSWORD: ${AUTH_SMTP_PASSWORD}
      SMTP_TLS: ${AUTH_SMTP_TLS}
      SYSTEM_EMAIL_ADDRESS: ${AUTH_SYSTEM_EMAIL_ADDRESS}
      JWT_PRIVATE_KEY: ${JWT_PRIVATE_KEY}
    working_dir: /system/auth/core
    command: "cargo watch -x run"
    depends_on:
      - auth_db
    tty: true

  # Auth server DB
  auth_db:
    container_name: meower_auth_db
    build:
      context: .
      dockerfile: ./docker/services/postgres/Dockerfile
    ports:
      - ${AUTH_DB_PORT}:${AUTH_DB_PORT}
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${AUTH_DB_NAME}
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
      POSTGRES_INITDB_ARGS: --encoding=UTF-8
    command: ["-c", "max_connections=200", "-p", "${AUTH_DB_PORT}"]
    restart: always
    tty: true

  # App server
  app:
    container_name: meower_app
    build:
      context: .
      dockerfile: ./docker/services/app/Dockerfile
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - ./system/app:/system/app
      - ./system/app/spa/dist:/system/app/core/public
      - ./system/auth/shared:/system/auth/shared
      - ./system/common:/system/common
      - ./env/${ENV}/${JWT_PUBLIC_KEY}:/system/app/core/env/${JWT_PUBLIC_KEY}
    environment:
      PORT: ${APP_PORT}
      DATABASE_URL: ${APP_DB_URL}
      CLIENT_ID_KEY: ${CLIENT_ID_KEY}
      CLIENT_SECRET_KEY: ${CLIENT_SECRET_KEY}
      CLIENT_ID: ${MEOWER_CLIENT_ID}
      CLIENT_SECRET: ${MEOWER_CLIENT_SECRET}
      AUTH_LOGIN_URL: ${APP_AUTH_LOGIN_URL}
      AUTH_REQUEST_TOKEN_URL: ${APP_AUTH_REQUEST_TOKEN_URL}
      JWT_PUBLIC_KEY: ${JWT_PUBLIC_KEY}
    working_dir: /system/app/core
    command: "cargo watch -x run"
    depends_on:
      - app_db
    tty: true

  # App server DB
  app_db:
    container_name: meower_app_db
    build:
      context: .
      dockerfile: ./docker/services/postgres/Dockerfile
    ports:
      - ${APP_DB_PORT}:${APP_DB_PORT}
    volumes:
      - app_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${APP_DB_NAME}
      POSTGRES_USER: ${APP_DB_USER}
      POSTGRES_PASSWORD: ${APP_DB_PASSWORD}
      POSTGRES_INITDB_ARGS: --encoding=UTF-8
    command: ["-c", "max_connections=200", "-p", "${APP_DB_PORT}"]
    restart: always
    tty: true

  # Application SPA
  app_spa:
    container_name: meower_app_spa
    build:
      context: .
      dockerfile: ./docker/services/spa/Dockerfile
    volumes:
      - ./system/app/spa:/system/app/spa
      - ./proto/ui_catalog/assets/scss:/system/app/spa/public/scss
    environment:
      API_URL: ${API_GW_URL}
    working_dir: /system/app/spa
    command: "trunk watch --release"
    tty: true


  ##############################################################################
  # Development tools
  ##############################################################################

  # Development tools
  dev:
    container_name: meower_dev
    build:
      context: .
      dockerfile: ./docker/services/dev/Dockerfile
    volumes:
      - ./system:/system
      - ./proto:/proto
    environment:
      APP_URL: ${APP_URL}
      MEOWER_CLIENT_ID: ${MEOWER_CLIENT_ID}
      MEOWER_CLIENT_SECRET: ${MEOWER_CLIENT_SECRET}
      MEOWER_REDIRECT_URI: ${MEOWER_REDIRECT_URI}
    tty: true

  # mailhog
  mailhog:
    container_name: meower_mailhog
    image: mailhog/mailhog:latest
    ports:
      - ${MAILHOG_PORT}:8025
      - ${MAILHOG_SMTP_PORT}:1025
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /tmp
    volumes:
      - mailhog_data:/tmp

  # tbls
  tbls:
    container_name: meower_tbls
    image: k1low/tbls:latest
    volumes:
      - ${TBLS_OUTPUT_PATH}:/work
    working_dir: /work
    depends_on:
      - auth_db
      - app_db
    tty: true

  # UI catalog
  ui:
    container_name: meower_ui
    build:
      context: .
      dockerfile: ./docker/services/ui/Dockerfile
    ports:
      - ${UI_CATALOG_PORT}:8030
    volumes:
      - ./proto/ui_catalog:/proto/ui_catalog
      - ui_catalog_node_modules:/proto/ui_catalog/node_modules
    working_dir: /proto/ui_catalog
    command: "npx gulp"
    tty: true


################################################################################
# Volumes
################################################################################
volumes:
  auth_db_data:
  app_db_data:
  mailhog_data:
  ui_catalog_node_modules:
