################################################################################
# Docker containers
################################################################################


################################################################################
# Services
################################################################################
services:

  ##############################################################################
  # System containers
  ##############################################################################

  # Load balancer
  balancer:
    container_name: meower_balancer
    build:
      context: .
      dockerfile: ./docker/system/balancer/Dockerfile
    ports:
      - ${BALANCER_PORT}:8080
    volumes:
      - ./docker/system/balancer/nginx.conf:/etc/nginx/nginx.conf

  # Postgres
  postgres:
    container_name: meower_postgres
    build:
      context: .
      dockerfile: ./docker/system/postgres/Dockerfile
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: --encoding=UTF-8
    command: ["-c", "max_connections=200"]
    restart: always
    tty: true


  ##############################################################################
  # Development tools
  ##############################################################################

  # mailhog
  mailhog:
    container_name: meower_mailhog
    image: mailhog/mailhog:latest
    ports:
      - ${MAILHOG_PORT}:8025
      - ${MAILHOG_SMTP_PORT}:1025
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /tmp
    volumes:
      - mailhog-data:/tmp

  # tbls
  tbls:
    container_name: meower_tbls
    image: k1low/tbls:latest
    volumes:
      - ${TBLS_OUTPUT_PATH}:/work
    working_dir: /work
    environment:
      TBLS_DSN: ${TBLS_DSN}
      TBLS_DOC_PATH: /work/${TBLS_DOC_PATH}
    depends_on:
      - postgres
    tty: true


################################################################################
# Volumes
################################################################################
volumes:
  pg-data:
  mailhog-data:
