################################################################################
# SPA.
################################################################################
FROM node:latest

WORKDIR /proto/ui_catalog
COPY proto/ui_catalog/package.json /proto/ui_catalog/package.json
RUN npm install
