[package]
name = "meower_auth_proxy"
version = "0.1.0"
edition = "2021"


[dependencies]
askama = "0.12.1"
axum = "0.6.20"
hyper = { version = "0.14.27", features = ["client"] }
tokio = { version = "1.34.0", features = ["full"] }
tower = "0.4.13"
tracing = "0.1.40"
