################################################################################
# Development container.
################################################################################
FROM rust_base AS base

RUN cargo install --locked sea-orm-cli grass
