################################################################################
# Development container.
################################################################################
FROM rust_base AS base

RUN rustup  component add rustfmt
RUN cargo install --locked sea-orm-cli grass
