################################################################################
# Docker containers
################################################################################

services:

  ##############################################################################
  # Develop tools
  ##############################################################################
  dev:
    container_name: meower_dev
    build:
      context: .
      dockerfile: ./docker/service/dev/Dockerfile
    volumes:
      - ./system:/system
    env_file: .env
    tty: true

  ##############################################################################
  # Load balancer
  ##############################################################################
  balancer:
    container_name: meower_balancer
    build:
      context: .
      dockerfile: ./docker/service/balancer/Dockerfile
    ports:
      - ${BALANCER_PORT}:8080
    volumes:
      - ./docker/service/balancer/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - entrance1
      - entrance2
      - backend1
      - backend2

  ##############################################################################
  # Entrance server
  ##############################################################################
  entrance1:
    container_name: meower_entrance1
    build:
      context: .
      dockerfile: ./docker/service/entrance/Dockerfile
    ports:
      - ${ENTRANCE1_PORT}:9000
    volumes:
      - ./system/assets:/system/assets
      - ./system/config:/system/config
      - ./system/entrance:/system/entrance
      - ./system/core:/system/core
      - ./system/datastore:/system/datastore
    env_file: .env
    environment:
      ENTRANCE_PORT: ${ENTRANCE1_PORT}
      FRONTEND_URL: ${FRONTEND1_URL}
    working_dir: /system/entrance
    command: "cargo watch -x run"
    depends_on:
      - postgres
    tty: true

  entrance2:
    container_name: meower_entrance2
    build:
      context: .
      dockerfile: ./docker/service/entrance/Dockerfile
    ports:
      - ${ENTRANCE2_PORT}:9001
    volumes:
      - ./system/assets:/system/assets
      - ./system/config:/system/config
      - ./system/entrance:/system/entrance
      - ./system/core:/system/core
      - ./system/datastore:/system/datastore
    env_file: .env
    environment:
      ENTRANCE_PORT: ${ENTRANCE2_PORT}
      FRONTEND_URL: ${FRONTEND2_URL}
    working_dir: /system/entrance
    command: "cargo watch -x run"
    depends_on:
      - postgres
    tty: true

  ##############################################################################
  # Front-end application
  ##############################################################################
  frontend1:
    container_name: meower_frontend1
    build:
      context: .
      dockerfile: ./docker/service/frontend/Dockerfile
    ports:
      - ${FRONTEND1_PORT}:9100
    volumes:
      - ./system/assets:/system/assets
      - ./system/config:/system/config
      - ./system/core:/system/core
      - ./system/service/api_schema:/system/service/api_schema
      - ./system/service/frontend:/system/service/frontend
    env_file: .env
    working_dir: /system/service/frontend
    command: "trunk serve --address 0.0.0.0 --release --port ${FRONTEND1_PORT}"
    tty: true

  frontend2:
    container_name: meower_frontend2
    build:
      context: .
      dockerfile: ./docker/service/frontend/Dockerfile
    ports:
      - ${FRONTEND2_PORT}:9101
    volumes:
      - ./system/assets:/system/assets
      - ./system/config:/system/config
      - ./system/core:/system/core
      - ./system/service/api_schema:/system/service/api_schema
      - ./system/service/frontend:/system/service/frontend
    env_file: .env
    working_dir: /system/service/frontend
    command: "trunk serve --address 0.0.0.0 --release --port ${FRONTEND2_PORT}"
    tty: true

  ##############################################################################
  # Back-end application
  ##############################################################################
  backend1:
    container_name: meower_backend1
    build:
      context: .
      dockerfile: ./docker/service/backend/Dockerfile
    ports:
      - ${BACKEND1_PORT}:9200
    volumes:
      - ./system/assets:/system/assets
      - ./system/config:/system/config
      - ./system/core:/system/core
      - ./system/service/api_schema:/system/service/api_schema
      - ./system/service/backend:/system/service/backend
      - ./system/datastore:/system/datastore
    env_file: .env
    environment:
      BACKEND_PORT: ${BACKEND1_PORT}
    working_dir: /system/service/backend
    command: "cargo watch -x run"
    depends_on:
      - postgres
    tty: true

  backend2:
    container_name: meower_backend2
    build:
      context: .
      dockerfile: ./docker/service/backend/Dockerfile
    ports:
      - ${BACKEND2_PORT}:9201
    volumes:
      - ./system/assets:/system/assets
      - ./system/config:/system/config
      - ./system/core:/system/core
      - ./system/service/api_schema:/system/service/api_schema
      - ./system/service/backend:/system/service/backend
      - ./system/datastore:/system/datastore
    env_file: .env
    environment:
      BACKEND_PORT: ${BACKEND2_PORT}
    working_dir: /system/service/backend
    command: "cargo watch -x run"
    depends_on:
      - postgres
    tty: true


  ##############################################################################
  # PostgreSQL database
  ##############################################################################
  postgres:
    container_name: meower_postgres
    build:
      context: .
      dockerfile: ./docker/service/postgres/Dockerfile
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_INITDB_ARGS: --encoding=UTF-8
    command: ["-c", "max_connections=200"]
    restart: always
    tty: true

  ##############################################################################
  # SMTP server
  ##############################################################################
  mail:
    container_name: meower_smtp
    image: mailhog/mailhog:latest
    ports:
      - ${MAILHOG_PORT}:8025
      - ${SMTP_PORT}:1025
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /tmp
    volumes:
      - mailhog-data:/tmp

  ##############################################################################
  # Output table definitions
  ##############################################################################
  tbls:
    container_name: meower_tbls
    image: k1low/tbls:latest
    volumes:
      - ../spec:/work
    working_dir: /work
    environment:
      TBLS_DSN: ${DATABASE_URL}
      TBLS_DOC_PATH: /work/database_design
    depends_on:
      - postgres
    tty: true


################################################################################
# Volumes
################################################################################
volumes:
  pg-data:
  mailhog-data:
